language: python
python:
- 3.8

env:
  PYPI_TOKEN:
    secure: FuztHQNl7hiQf4VcUBMy7vPtbmNNpzZbgncgoKDkyDTEXPga0RGEuKBpSNEUJxYeef+q/ppJSlFC6sXDSXvJEyw3KoJEjYCRVSVFCpalgjqsRMYdrux5n4c1tuPGx8c3SJ/ErVWRBzidcEyAiBNyeELvBOJjWFMHj7avKduDGrozfPLpBpe4pJtBIA4vC4VofZxEvoehbps9kmpA8/ZWs3zgnFlvuL1IpjEHuI0mUyMCh1Pneo01Mm6bh3TPXt+EwrkupkN4oxzu7040eMfUX1QEGoZsKftWJa39UevJ9aPaY05yg952UmPS5ps34qJ1RuRU3mg10Ge0wa8GLiU6cks1Q0GpGYzBuLsLOyEpk0mdtncyK4r5hjoLkSVyHXRF6uRq1OJVM8HRTfUiOOcXV3XemZhX7MazLug1oxis28eRctw63NqZMOSvv6m/i7Ur754S9ZxhN5D8r2zc5ZFxHTnSnPO2HXT7M4CYl+OtX1EMvLTOOKxF4D6pR9qdVM7JPCenh9T2OwtTNRKA5+VOV82vAW/ei3SAewFbSgGJ5QxbIlimvlV9X7MG6zlfkZWDum9Ewdej/JyukFJWunSdccCpfaymHNnz2s2TwcOGNzqLjbfc5ZQmrgev63CRvmNoQXCLGj7gNAsh4WYj+O/ANOmM/PNqGFi1NijGvc+fT1U=

script:
- pip install twine pytest
- pip install -e .
  #- pytest -s
- python setup.py sdist bdist_wheel
- twine check dist/*
- if [ "$TRAVIS_BRANCH" = "main" ]; then twine upload --skip-existing dist/* -u __token__
  -p $PYPI_TOKEN; fi
